project:
  type: book

book:
  title: "Documentation for Sierra Nevada Passive Acoustic Monitoring Program"
  author: "Jay Winiarski"
  date: "11/4/2024"
  chapters:
    - index.qmd
    - fieldwork.qmd
    - data_storage.qmd
    - data_processing.qmd
    - csow_bdow_vetting.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

